version: '3'

services:
  library_api:
    container_name: library_api
    build:
      context: ./
      # dockerfile: Dockerfile
    environment:
      - SECRET_KEY=L8c@4s0lk8$hdW
      - DATABASE_URL=mongodb://root:root@mongo:27017/library_api?authSource=admin
      - PORT=3000
    volumes:
      # - './:/api'
      - ./node_modules
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  mongo:
    image: 'mongo:latest'
    container_name: mongo
    ports:
      - '27017:27017'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - './mongo/data/db:/data/db'
      - './mongo/data/configdb:/data/configdb'

volumes:
  mongodb_data:
    driver: local
  initMongo:
    driver: local